services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=bitnami
      - MARIADB_ROOT_PASSWORD=bitnamiroot
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - '/docker/moodle/mariadb_data:/bitnami'
  moodle:
    image: docker.io/bitnami/moodle:5.0
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=bitnameroot
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_USERNAME=user
      - MOODLE_PASSWORD=bitname
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - '/docker/moodle/moodledata:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local